### ISSUE TITLE
Search the whole search tree for a solution

### ISSUE THREAD

**Issue by pevnak** [Josek20/MetaProject#9]
If we have rules, which can increase the size of the expression, you cannot search only leaves, but also inner nodes, because there could be a small expressions which was rewritten to large one.

**Comment by Josek20** [comment]
![a1](https://github.com/user-attachments/assets/b3bd611d-42dc-445a-b0a8-06e4e2330776)

**Comment by Josek20** [comment]
I look into all nodes in the tree
